baseURL = 'https://bruno.moe/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'Bruno'
enableRobotsTXT = true

[params]
  description = 'Minha página'
  author = 'Bruno'

[permalinks]
  ensaios = '/ensaios/:slug'

[taxonomies]
  categoria = 'categorias'
  tag = 'tags'
  serie = 'series'

[markup.tableOfContents]
  startLevel = 2
  endLevel   = 4
  ordered    = true

[markup.goldmark.renderer]
  unsafe = true

[security]
  enableInlineShortcodes = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']

[[menus.main]]
  name    = 'Home'
  pageRef = '/'
  weight  = 10

[[menus.main]]
  name    = 'Ensaios'
  pageRef = '/ensaios'
  weight  = 20

[[menus.main]]
  name    = 'Categorias'
  pageRef = '/categorias'
  weight  = 30

[[menus.main]]
  name    = 'Séries'
  pageRef = '/series'
  weight  = 40