baseURL = 'https://bruno.moe/'
languageCode = 'pt-br'
title = 'Blog do Bruno'

[params]
  description = 'Meu blog pessoal sobre tecnologia e desenvolvimento'
  author = 'Bruno'

[permalinks]
  artigos = '/artigos/:slug'

[taxonomies]
  categoria = 'categorias'
  tag      = 'tags'
  serie    = 'series'

[markup.tableOfContents]
  startLevel = 2
  endLevel   = 4
  ordered    = true

[markup.goldmark.renderer]
  unsafe = true

[security]
  enableInlineShortcodes = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']

[security.exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^tailwindcss$']
  osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[security.http]
  methods = ['(?i)GET|POST']
  urls    = ['.*']

[[menus.main]]
  name    = 'Home'
  pageRef = '/'
  weight  = 10

[[menus.main]]
  name    = 'Artigos'
  pageRef = '/artigos'
  weight  = 20

[[menus.main]]
  name    = 'Categorias'
  pageRef = '/categorias'
  weight  = 30

[[menus.main]]
  name    = 'SÃ©ries'
  pageRef = '/series'
  weight  = 40